package com.fyn_monolithic.model.event;

public enum ActivityType {
    COFFEE, BREAKFAST, BRUNCH, LUNCH, DINNER, DRINKS,
    SPORTS, GYM, HIKING, CYCLING, RUNNING, SWIMMING,
    MOVIE, CONCERT, THEATER, MUSEUM, EXHIBITION,
    STUDY, TUTORING, WORKSHOP, SEMINAR, CONFERENCE,
    GAMING, BOARD_GAMES, ESPORTS,
    TRAVEL, ROAD_TRIP, CAMPING,
    NETWORKING, MEETUP, COWORKING,
    VOLUNTEER, CHARITY,
    PARTY, CELEBRATION,
    OTHER
}
